name: Build Zed Nightly GLES

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    env:
      RUSTFLAGS: "--cfg gles"
    steps:
      - uses: actions/checkout@v3
        with:
          repository: zed-industries/zed
          ref: main

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: wasm32-wasi

      - uses: Swatinem/rust-cache@v2

      - name: Build release
        run: cargo build --release

      - uses: actions/upload-artifact@v4
        with:
          name: zed-release-windows-gles
          path: target/release/zed.exe

  release:
    needs: build
    runs-on: ubuntu-latest
    env:
      TAG_NAME:
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: zed-release-windows-gles
      - uses: actions/checkout@v3
        with:
          repository: zed-industries/zed
          ref: main
      - run: |
          echo "TAG_NAME=$(tr -dc 'a-f0-9' < /dev/urandom | head -c8)" >> $GITHUB_ENV
          git rev-list --format=%B --max-count=1 main | tee ./commit_desc.txt >/dev/null

      - uses: softprops/action-gh-release@v2
        with:
          name: "zed-release-windows-gles-${{ env.TAG_NAME }}"
          tag_name: ${{ env.TAG_NAME }}
          draft: false
          make_latest: true
          body_path: "./commit_desc.txt"
          files: zed.exe