name: Build Zed Nightly

on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:
    inputs:
      rustflags:
        type: choice
        options:
          - --cfg gles
          - " "

jobs:
  build:
    runs-on: windows-latest
    #env:
      #RUSTFLAGS: ${{ github.event.inputs.rustflags }}
    steps:
      - uses: actions/checkout@v4
        with:
          repository: zed-industries/zed
          ref: main

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          targets: wasm32-wasip1

      - uses: Swatinem/rust-cache@v2

      - name: Build release
        run: |
          git config --system core.longpaths true
          cargo build --release

      - uses: actions/upload-artifact@v4
        with:
          name: zed-release
          path: target/release/zed.exe

  release:
    needs: build
    runs-on: ubuntu-latest
    env:
      TAG_NAME:
      RELEASE_NAME:
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          repository: zed-industries/zed
          ref: main

      - run: |
          echo "TAG_NAME=$(tr -dc 'a-f0-9' 2>/dev/null < /dev/urandom | head -c8)" >> $GITHUB_ENV
          echo "RELEASE_NAME=$([[ "${{ github.event.inputs.rustflags }}" == *"gles"* ]] && echo zed-windows-gles || echo zed-windows)" >> $GITHUB_ENV

      - uses: actions/download-artifact@v4
        with:
          name: zed-release

      - name: Compress zed binary
        run: zip -rv9 Zed.zip zed.exe

      - uses: softprops/action-gh-release@v2
        with:
          name: ${{ env.RELEASE_NAME }}-${{ env.TAG_NAME }}
          tag_name: ${{ env.TAG_NAME }}
          draft: false
          make_latest: true
          files: Zed.zip
